name: null
favicon: null
layout_spectrum: 0.04225
typography_spectrum: 0.46055
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#431c5d'
    - '#c2dde6'
    - '#e05915'
    - '#cdd422'
    - '#a57882'
  brandStrength: 0
  lightness: 0.5625
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
