name: vizualiphone
favicon: null
layout_spectrum: 0.38319
typography_spectrum: 0.48928
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e5dad6'
    - '#90c9d8'
    - '#3c95a1'
    - '#ec7088'
    - '#30465d'
  brandStrength: 0
  lightness: 0.8125
  saturation: 0.125
  rhythmicContrast: 0.25
purpose: []
