name: null
favicon: null
layout_spectrum: 0.22547
typography_spectrum: 0.46055
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b3c2bf'
    - '#e9ece5'
    - '#3b3a36'
    - '#595c58'
    - '#a2a3a2'
  brandStrength: 0
  lightness: 0.5625
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
