name: vizualiphone
favicon: null
layout_spectrum: 0.38319
typography_spectrum: 0.48928
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#edf6f9'
    - '#36cfe3'
    - '#ed6f88'
    - '#000000'
    - '#4d5862'
  brandStrength: 0
  lightness: 0.8125
  saturation: 0.125
  rhythmicContrast: 0.25
purpose: []
