name: null
favicon: null
layout_spectrum: 0.22547
typography_spectrum: 0.46055
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e3e0cf'
    - '#9fa8a3'
    - '#c5d5cb'
    - '#ffffff'
    - '#b0b6ae'
  brandStrength: 0
  lightness: 0.5625
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
