name: null
favicon: null
layout_spectrum: 0.17239
typography_spectrum: 0.46055
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9b7f1a'
    - '#c2996a'
    - '#6f5219'
    - '#ede6d5'
    - '#fc7665'
  brandStrength: 0
  lightness: 0.5625
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
