name: myothercamera.is
favicon: null
layout_spectrum: 0.40247
typography_spectrum: 0.9781
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f22539'
    - '#cabbc2'
    - '#80d8ed'
    - '#fc4b60'
    - '#eb98a2'
  brandStrength: 0
  lightness: 0.9375
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
