name: null
favicon: null
layout_spectrum: 0.12555
typography_spectrum: 0.19915
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#dbdbdd'
    - '#b1adae'
    - '#c7c5c8'
    - '#999393'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
purpose: []
