name: vizualiphone
favicon: null
layout_spectrum: 0.08341
typography_spectrum: 0.32334
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c9c9c9'
    - '#9ad3de'
    - '#89bdd3'
    - '#e3e3e3'
    - '#fefefe'
  brandStrength: 0
  lightness: 0.375
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
