name: vizualiphone
favicon: null
layout_spectrum: 0.39736
typography_spectrum: 0.48928
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e5dad6'
    - '#90cad8'
    - '#3d95a1'
    - '#ec7088'
    - '#30465d'
  brandStrength: 0
  lightness: 0.8125
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
