name: null
favicon: null
layout_spectrum: 1
typography_spectrum: 0.23922
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#ffbcb6'
    - '#fd5064'
    - '#8f9964'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.4375
  rhythmicContrast: 1
purpose: []
